# Generated by Django 3.2.3 on 2021-05-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='Foto',
            field=models.CharField(default='NO', max_length=256),
            preserve_default=False,
        ),
    ]
