# Generated by Django 3.2.3 on 2021-05-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_proyecto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='Foto',
            field=models.CharField(max_length=256),
        ),
    ]
