# Generated by Django 3.2.3 on 2021-11-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_proyecto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='Descripcion',
            field=models.CharField(default='nada', max_length=256),
            preserve_default=False,
        ),
    ]
