# Generated by Django 3.2.3 on 2021-11-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_proyecto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='Foto',
            field=models.FileField(upload_to=''),
        ),
    ]
