# Generated by Django 3.2.3 on 2021-11-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_proyecto_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('RazonSocial', models.CharField(max_length=256)),
                ('SobreMi', models.TextField(max_length=256)),
                ('Edad', models.IntegerField()),
                ('Mail', models.CharField(max_length=70)),
            ],
        ),
    ]
