# Generated by Django 3.2.3 on 2021-11-06 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='Imagen',
            field=models.FileField(default='ok', upload_to=''),
            preserve_default=False,
        ),
    ]
