# Generated by Django 3.2.3 on 2021-11-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_perfil_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=256)),
                ('Fecha', models.DateField()),
                ('Certificado', models.FileField(upload_to='')),
                ('Lugar', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Nivel', models.CharField(max_length=20)),
            ],
        ),
    ]
