# Generated by Django 3.2.3 on 2021-11-08 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20211107_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='Foto',
            field=models.FileField(default='a', upload_to=''),
            preserve_default=False,
        ),
    ]
