# Generated by Django 3.2.3 on 2021-11-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_perfil_fotofondo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='CV',
            field=models.FileField(default='a', upload_to=''),
            preserve_default=False,
        ),
    ]
