# Generated by Django 3.2.3 on 2022-01-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_perfil_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Lugar', models.CharField(max_length=100)),
                ('Desde', models.DateField()),
                ('Hasta', models.DateField()),
                ('Tecnologias', models.CharField(max_length=256)),
                ('Referencia', models.CharField(max_length=100, null=True)),
                ('Descripcion', models.TextField(max_length=256)),
            ],
        ),
    ]
